from __future__ import annotations

from .contracts import RiskLevel, SkillSpec, SkillStatus, UpstreamProject


def up(name: str, url: str, license: str | None, boundary: str = "optional_adapter") -> UpstreamProject:
    return UpstreamProject(name=name, url=url, license=license, boundary=boundary)


def schema(properties: dict[str, object], required: list[str] | None = None) -> dict[str, object]:
    return {"type": "object", "properties": properties, "required": required or []}


SKILLS: tuple[SkillSpec, ...] = (
    SkillSpec(
        id="messaging.wechat.personal.official_boundary",
        name_zh="个人微信官方插件边界",
        name_en="Personal WeChat Official Plugin Boundary",
        domain="messaging",
        summary="Records Tencent's official openclaw-weixin plugin as the supported personal WeChat boundary.",
        entrypoint="panclaw.adapters.messaging:wechat_personal_boundary",
        upstreams=(up("Tencent openclaw-weixin", "https://github.com/Tencent/openclaw-weixin", None, "official_openclaw_plugin"),),
        permissions=("messaging:wechat:read_config",),
        risk_level=RiskLevel.REGULATED,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="openclaw_channel_plugin",
        license_boundary="official_terms_required",
        tags=("wechat", "personal-wechat", "openclaw-weixin", "official-plugin"),
        notes="Use Tencent/openclaw-weixin; do not use reverse-engineered personal WeChat protocols.",
    ),
    SkillSpec(
        id="messaging.wechat.personal.openclaw_weixin.info",
        name_zh="个人微信插件信息",
        name_en="OpenClaw Weixin Plugin Info",
        domain="messaging",
        summary="Returns Tencent openclaw-weixin official plugin metadata.",
        entrypoint="panclaw.adapters.openclaw_weixin:official_plugin_info",
        upstreams=(up("Tencent openclaw-weixin", "https://github.com/Tencent/openclaw-weixin", None, "official_openclaw_plugin"),),
        permissions=("messaging:wechat:read_config",),
        risk_level=RiskLevel.LOW,
        status=SkillStatus.READY,
        sandbox="local_readonly",
        license_boundary="official_terms_required",
        tags=("wechat", "openclaw-weixin", "official-plugin"),
    ),
    SkillSpec(
        id="messaging.wechat.personal.openclaw_weixin.quick_install",
        name_zh="个人微信插件快速安装",
        name_en="OpenClaw Weixin Quick Install",
        domain="messaging",
        summary="Installs Tencent's official @tencent-weixin/openclaw-weixin plugin through its official CLI.",
        entrypoint="panclaw.adapters.openclaw_weixin:quick_install",
        upstreams=(up("Tencent openclaw-weixin", "https://github.com/Tencent/openclaw-weixin", None, "official_openclaw_plugin"),),
        input_schema=schema({"dry_run": {"type": "boolean"}}, []),
        permissions=("subprocess:execute", "network:egress", "openclaw:plugin_mutate"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="external_cli",
        license_boundary="official_terms_required",
        tags=("wechat", "openclaw-weixin", "install"),
    ),
    SkillSpec(
        id="messaging.wechat.personal.openclaw_weixin.manual_install",
        name_zh="个人微信插件手动安装",
        name_en="OpenClaw Weixin Manual Install",
        domain="messaging",
        summary="Runs OpenClaw plugin install/enable commands for Tencent openclaw-weixin.",
        entrypoint="panclaw.adapters.openclaw_weixin:manual_install",
        upstreams=(up("Tencent openclaw-weixin", "https://github.com/Tencent/openclaw-weixin", None, "official_openclaw_plugin"),),
        input_schema=schema({"restart_gateway": {"type": "boolean"}, "dry_run": {"type": "boolean"}}, []),
        permissions=("subprocess:execute", "network:egress", "openclaw:plugin_mutate"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="external_cli",
        license_boundary="official_terms_required",
        tags=("wechat", "openclaw-weixin", "install"),
    ),
    SkillSpec(
        id="messaging.wechat.personal.openclaw_weixin.login",
        name_zh="个人微信扫码登录",
        name_en="OpenClaw Weixin QR Login",
        domain="messaging",
        summary="Starts the official OpenClaw Weixin QR login flow.",
        entrypoint="panclaw.adapters.openclaw_weixin:login",
        upstreams=(up("Tencent openclaw-weixin", "https://github.com/Tencent/openclaw-weixin", None, "official_openclaw_plugin"),),
        input_schema=schema({"dry_run": {"type": "boolean"}}, []),
        permissions=("subprocess:execute", "wechat:qr_login", "openclaw:channel_login"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="external_cli",
        license_boundary="official_terms_required",
        tags=("wechat", "openclaw-weixin", "login"),
    ),
    SkillSpec(
        id="messaging.wechat.personal.openclaw_weixin.status",
        name_zh="个人微信插件状态",
        name_en="OpenClaw Weixin Status",
        domain="messaging",
        summary="Checks OpenClaw version, plugins and channels for the official Weixin plugin.",
        entrypoint="panclaw.adapters.openclaw_weixin:status",
        upstreams=(up("Tencent openclaw-weixin", "https://github.com/Tencent/openclaw-weixin", None, "official_openclaw_plugin"),),
        input_schema=schema({"dry_run": {"type": "boolean"}}, []),
        permissions=("subprocess:execute", "openclaw:read_config"),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=False,
        sandbox="external_cli",
        license_boundary="official_terms_required",
        tags=("wechat", "openclaw-weixin", "status"),
    ),
    SkillSpec(
        id="messaging.wechat.official_account.customer_service_send",
        name_zh="微信公众号客服消息",
        name_en="WeChat Official Account Customer Service Send",
        domain="messaging",
        summary="Sends a customer-service text message through the official WeChat Official Account API.",
        entrypoint="panclaw.adapters.messaging:wechat_official_customer_service_send",
        upstreams=(up("WeChat Official Account API", "https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Service_Center_messages.html", None, "official_service"),),
        input_schema=schema({"openid": {"type": "string"}, "text": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["openid", "text"]),
        permissions=("network:egress", "messaging:send", "wechat:official_account"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="network_adapter",
        license_boundary="official_terms_required",
        tags=("wechat", "official-account", "customer-service"),
        notes="Official Account API only; does not automate a personal WeChat account.",
    ),
    SkillSpec(
        id="messaging.wecom.webhook.send",
        name_zh="企业微信发送",
        name_en="WeCom Webhook Send",
        domain="messaging",
        summary="Sends text to a configured WeCom group robot webhook.",
        entrypoint="panclaw.adapters.messaging:wecom_send",
        upstreams=(up("WeCom API", "https://developer.work.weixin.qq.com/", None, "official_service"),),
        input_schema=schema({"text": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["text"]),
        permissions=("network:egress", "messaging:send"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="network_adapter",
        license_boundary="official_terms_required",
        tags=("wecom", "wechat-work", "webhook"),
    ),
    SkillSpec(
        id="messaging.feishu.webhook.send",
        name_zh="飞书发送",
        name_en="Feishu Webhook Send",
        domain="messaging",
        summary="Sends text to a configured Feishu/Lark bot webhook.",
        entrypoint="panclaw.adapters.messaging:feishu_send",
        upstreams=(up("Feishu Open Platform", "https://open.feishu.cn/", None, "official_service"),),
        input_schema=schema({"text": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["text"]),
        permissions=("network:egress", "messaging:send"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="network_adapter",
        license_boundary="official_terms_required",
        tags=("feishu", "lark", "webhook"),
    ),
    SkillSpec(
        id="messaging.lark.webhook.send",
        name_zh="Lark 发送",
        name_en="Lark Webhook Send",
        domain="messaging",
        summary="Sends text to a configured Lark custom bot webhook.",
        entrypoint="panclaw.adapters.messaging:lark_send",
        upstreams=(up("Lark Open Platform", "https://open.larksuite.com/", None, "official_service"),),
        input_schema=schema({"text": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["text"]),
        permissions=("network:egress", "messaging:send"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="network_adapter",
        license_boundary="official_terms_required",
        tags=("lark", "webhook"),
    ),
    SkillSpec(
        id="messaging.dingtalk.webhook.send",
        name_zh="钉钉发送",
        name_en="DingTalk Webhook Send",
        domain="messaging",
        summary="Sends text to a configured DingTalk robot webhook.",
        entrypoint="panclaw.adapters.messaging:dingtalk_send",
        upstreams=(up("DingTalk Open Platform", "https://open.dingtalk.com/", None, "official_service"),),
        input_schema=schema({"text": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["text"]),
        permissions=("network:egress", "messaging:send"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="network_adapter",
        license_boundary="official_terms_required",
        tags=("dingtalk", "webhook"),
    ),
    SkillSpec(
        id="messaging.channels.health",
        name_zh="官方渠道健康检查",
        name_en="Official Channel Health",
        domain="messaging",
        summary="Reports sanitized configuration status for OpenClaw Weixin, WeChat Official Account, WeCom, Feishu, Lark and DingTalk.",
        entrypoint="panclaw.adapters.messaging:official_channel_health",
        upstreams=(
            up("Tencent openclaw-weixin", "https://github.com/Tencent/openclaw-weixin", None, "official_openclaw_plugin"),
            up("WeCom API", "https://developer.work.weixin.qq.com/", None, "official_service"),
            up("Feishu Open Platform", "https://open.feishu.cn/", None, "official_service"),
            up("Lark Open Platform", "https://open.larksuite.com/", None, "official_service"),
            up("DingTalk Open Platform", "https://open.dingtalk.com/", None, "official_service"),
        ),
        input_schema=schema({"dry_run": {"type": "boolean"}}, []),
        permissions=("messaging:read_config", "openclaw:read_config"),
        risk_level=RiskLevel.LOW,
        status=SkillStatus.READY,
        sandbox="local_readonly",
        license_boundary="official_terms_required",
        tags=("wechat", "wecom", "feishu", "lark", "dingtalk", "health"),
    ),
    SkillSpec(
        id="office.pdf.extract",
        name_zh="PDF 解析",
        name_en="PDF Extract",
        domain="office_pdf",
        summary="Extracts text and metadata from PDF files through PyMuPDF when installed.",
        entrypoint="panclaw.adapters.office_pdf:pdf_extract",
        upstreams=(up("PyMuPDF", "https://github.com/pymupdf/PyMuPDF", "AGPL/commercial", "external_or_license_gated"),),
        input_schema=schema({"path": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["path"]),
        permissions=("filesystem:read",),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.LICENSE_GATED,
        sandbox="local_file_adapter",
        license_boundary="external_or_license_review",
        tags=("pdf", "pymupdf"),
    ),
    SkillSpec(
        id="office.docx.generate",
        name_zh="Word 文档生成",
        name_en="DOCX Generate",
        domain="office_pdf",
        summary="Generates Word documents through python-docx when installed.",
        entrypoint="panclaw.adapters.office_pdf:docx_generate",
        upstreams=(up("python-docx", "https://github.com/python-openxml/python-docx", "MIT", "optional_adapter"),),
        input_schema=schema({"title": {"type": "string"}, "paragraphs": {"type": "array"}, "output_path": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["output_path"]),
        permissions=("filesystem:write",),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="local_file_adapter",
        tags=("docx", "office"),
    ),
    SkillSpec(
        id="office.xlsx.generate",
        name_zh="Excel 表格生成",
        name_en="XLSX Generate",
        domain="office_pdf",
        summary="Generates spreadsheets through openpyxl when installed.",
        entrypoint="panclaw.adapters.office_pdf:xlsx_generate",
        upstreams=(up("openpyxl", "https://foss.heptapod.net/openpyxl/openpyxl", "MIT", "optional_adapter"),),
        input_schema=schema({"rows": {"type": "array"}, "output_path": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["rows", "output_path"]),
        permissions=("filesystem:write",),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="local_file_adapter",
        tags=("xlsx", "office"),
    ),
    SkillSpec(
        id="image.pillow.process",
        name_zh="图片处理",
        name_en="Pillow Image Process",
        domain="image",
        summary="Runs basic image resize/convert operations through Pillow when installed.",
        entrypoint="panclaw.adapters.image_media:pillow_process",
        upstreams=(up("Pillow", "https://github.com/python-pillow/Pillow", "HPND", "optional_adapter"),),
        input_schema=schema({"input_path": {"type": "string"}, "output_path": {"type": "string"}, "max_size": {"type": "array"}, "dry_run": {"type": "boolean"}}, ["input_path", "output_path"]),
        permissions=("filesystem:read", "filesystem:write"),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="local_file_adapter",
        tags=("image", "pillow"),
    ),
    SkillSpec(
        id="image.stable_diffusion.webui.generate",
        name_zh="Stable Diffusion 生成",
        name_en="Stable Diffusion WebUI Generate",
        domain="image",
        summary="Calls a local Stable Diffusion WebUI API endpoint for image generation.",
        entrypoint="panclaw.adapters.image_media:stable_diffusion_generate",
        upstreams=(up("Stable Diffusion WebUI", "https://github.com/AUTOMATIC1111/stable-diffusion-webui", "AGPL-3.0", "external_service"),),
        input_schema=schema({"prompt": {"type": "string"}, "negative_prompt": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["prompt"]),
        permissions=("network:localhost", "artifact:write"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.EXTERNAL_SERVICE,
        approval_required=True,
        sandbox="local_http_service",
        license_boundary="external_service_only",
        tags=("image-generation", "stable-diffusion"),
    ),
    SkillSpec(
        id="audio.whisper.transcribe",
        name_zh="语音转文字",
        name_en="Whisper Transcribe",
        domain="audio_video",
        summary="Transcribes audio through a locally installed Whisper CLI.",
        entrypoint="panclaw.adapters.image_media:whisper_transcribe",
        upstreams=(up("Whisper", "https://github.com/openai/whisper", "MIT", "external_cli"),),
        input_schema=schema({"audio_path": {"type": "string"}, "language": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["audio_path"]),
        permissions=("filesystem:read", "subprocess:execute"),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="external_cli",
        tags=("audio", "transcription"),
    ),
    SkillSpec(
        id="video.ffmpeg.convert",
        name_zh="视频转换",
        name_en="FFmpeg Convert",
        domain="audio_video",
        summary="Runs FFmpeg conversion through an installed ffmpeg binary.",
        entrypoint="panclaw.adapters.image_media:ffmpeg_convert",
        upstreams=(up("FFmpeg", "https://github.com/FFmpeg/FFmpeg", "LGPL/GPL", "external_cli"),),
        input_schema=schema({"input_path": {"type": "string"}, "output_path": {"type": "string"}, "args": {"type": "array"}, "dry_run": {"type": "boolean"}}, ["input_path", "output_path"]),
        permissions=("filesystem:read", "filesystem:write", "subprocess:execute"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.LICENSE_GATED,
        approval_required=True,
        sandbox="external_cli",
        license_boundary="external_process_only",
        tags=("video", "ffmpeg"),
    ),
    SkillSpec(
        id="render.blender.python",
        name_zh="Blender 渲染",
        name_en="Blender Python Render",
        domain="three_d",
        summary="Runs Blender Python scripts through an installed Blender binary.",
        entrypoint="panclaw.adapters.image_media:blender_python",
        upstreams=(up("Blender", "https://github.com/blender/blender", "GPL-3.0", "external_cli"),),
        input_schema=schema({"script_path": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["script_path"]),
        permissions=("filesystem:read", "subprocess:execute"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.LICENSE_GATED,
        approval_required=True,
        sandbox="external_cli",
        license_boundary="external_process_only",
        tags=("3d", "rendering", "blender"),
    ),
    SkillSpec(
        id="desktop.pyautogui.control",
        name_zh="电脑控制",
        name_en="PyAutoGUI Desktop Control",
        domain="computer_control",
        summary="Controls local mouse/keyboard through PyAutoGUI when explicitly enabled.",
        entrypoint="panclaw.adapters.automation:pyautogui_control",
        upstreams=(up("PyAutoGUI", "https://github.com/asweigart/pyautogui", "BSD", "optional_adapter"),),
        input_schema=schema({"actions": {"type": "array"}, "dry_run": {"type": "boolean"}}, ["actions"]),
        permissions=("desktop:mouse", "desktop:keyboard"),
        risk_level=RiskLevel.DESTRUCTIVE,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="host_desktop",
        tags=("desktop", "automation"),
    ),
    SkillSpec(
        id="server.ansible.playbook",
        name_zh="服务器批量控制",
        name_en="Ansible Playbook",
        domain="computer_control",
        summary="Runs Ansible playbooks as external CLI jobs.",
        entrypoint="panclaw.adapters.automation:ansible_playbook",
        upstreams=(up("Ansible", "https://github.com/ansible/ansible", "GPL-3.0", "external_cli"),),
        input_schema=schema({"playbook": {"type": "string"}, "inventory": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["playbook"]),
        permissions=("network:egress", "subprocess:execute", "server:mutate"),
        risk_level=RiskLevel.DESTRUCTIVE,
        status=SkillStatus.LICENSE_GATED,
        approval_required=True,
        sandbox="external_cli",
        license_boundary="external_process_only",
        tags=("ansible", "server"),
    ),
    SkillSpec(
        id="observability.local.snapshot",
        name_zh="本机硬件状态",
        name_en="Local Hardware Snapshot",
        domain="observability",
        summary="Reports local CPU, memory and disk status; uses psutil when installed and stdlib fallback otherwise.",
        entrypoint="panclaw.adapters.automation:local_snapshot",
        upstreams=(up("psutil", "https://github.com/giampaolo/psutil", "BSD-3-Clause", "optional_adapter"),),
        input_schema=schema({"dry_run": {"type": "boolean"}}),
        permissions=("system:read",),
        risk_level=RiskLevel.LOW,
        status=SkillStatus.READY,
        sandbox="local_readonly",
        tags=("hardware", "monitoring"),
    ),
    SkillSpec(
        id="observability.prometheus.query",
        name_zh="Prometheus 查询",
        name_en="Prometheus Query",
        domain="observability",
        summary="Queries a configured Prometheus HTTP API.",
        entrypoint="panclaw.adapters.automation:prometheus_query",
        upstreams=(up("Prometheus", "https://github.com/prometheus/prometheus", "Apache-2.0", "external_service"),),
        input_schema=schema({"query": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["query"]),
        permissions=("network:egress",),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.EXTERNAL_SERVICE,
        sandbox="network_adapter",
        tags=("prometheus", "monitoring"),
    ),
    SkillSpec(
        id="cloud.terraform.plan",
        name_zh="Terraform 计划",
        name_en="Terraform Plan",
        domain="cloud",
        summary="Runs Terraform plan through an external CLI; apply is intentionally not exposed in v0.1.",
        entrypoint="panclaw.adapters.cloud_iac:terraform_plan",
        upstreams=(up("Terraform", "https://github.com/hashicorp/terraform", "BUSL/MPL split", "external_cli_or_license_review"),),
        input_schema=schema({"workdir": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["workdir"]),
        permissions=("filesystem:read", "subprocess:execute", "network:egress"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.LICENSE_GATED,
        approval_required=True,
        sandbox="external_cli",
        license_boundary="external_process_only",
        tags=("terraform", "iac"),
    ),
    SkillSpec(
        id="cloud.provider.create_server",
        name_zh="云服务器创建",
        name_en="Cloud Provider Create Server",
        domain="cloud",
        summary="Provider-neutral cloud server creation boundary for AWS, Alibaba Cloud and Tencent Cloud SDKs.",
        entrypoint="panclaw.adapters.cloud_iac:cloud_create_server",
        upstreams=(
            up("boto3", "https://github.com/boto/boto3", "Apache-2.0", "optional_adapter"),
            up("Alibaba Cloud SDK", "https://github.com/aliyun/alibabacloud-python-sdk", "Apache-2.0", "optional_adapter"),
            up("Tencent Cloud SDK", "https://github.com/TencentCloud/tencentcloud-sdk-python", "Apache-2.0", "optional_adapter"),
        ),
        input_schema=schema({"provider": {"type": "string"}, "region": {"type": "string"}, "instance_type": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["provider", "region"]),
        permissions=("network:egress", "cloud:mutate", "billing:mutate"),
        risk_level=RiskLevel.DESTRUCTIVE,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="network_adapter",
        tags=("aws", "aliyun", "tencent-cloud"),
    ),
    SkillSpec(
        id="finance.akshare.query",
        name_zh="AkShare 财经数据",
        name_en="AkShare Query",
        domain="finance",
        summary="Fetches China market and macro data through AkShare when installed.",
        entrypoint="panclaw.adapters.finance_life:akshare_query",
        upstreams=(up("AkShare", "https://github.com/akfamily/akshare", "Apache-2.0", "optional_adapter"),),
        input_schema=schema({"dataset": {"type": "string"}, "params": {"type": "object"}, "dry_run": {"type": "boolean"}}, ["dataset"]),
        permissions=("network:egress",),
        risk_level=RiskLevel.REGULATED,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        sandbox="network_adapter",
        tags=("finance", "market-data"),
        notes="Market data only; no investment advice.",
    ),
    SkillSpec(
        id="finance.tushare.query",
        name_zh="TuShare 财经数据",
        name_en="TuShare Query",
        domain="finance",
        summary="Fetches financial data through TuShare when installed and token is configured.",
        entrypoint="panclaw.adapters.finance_life:tushare_query",
        upstreams=(up("TuShare", "https://github.com/waditu/tushare", None, "external_service"),),
        input_schema=schema({"api": {"type": "string"}, "params": {"type": "object"}, "dry_run": {"type": "boolean"}}, ["api"]),
        permissions=("network:egress",),
        risk_level=RiskLevel.REGULATED,
        status=SkillStatus.EXTERNAL_SERVICE,
        sandbox="network_adapter",
        tags=("finance", "market-data"),
        notes="Market data only; no investment advice.",
    ),
    SkillSpec(
        id="commerce.browser.price_compare",
        name_zh="电商比价",
        name_en="Browser Price Compare",
        domain="commerce_life",
        summary="Uses browser automation for comparison research; checkout is not exposed.",
        entrypoint="panclaw.adapters.finance_life:browser_price_compare",
        upstreams=(up("Playwright", "https://github.com/microsoft/playwright", "Apache-2.0", "optional_adapter"),),
        input_schema=schema({"query": {"type": "string"}, "sites": {"type": "array"}, "dry_run": {"type": "boolean"}}, ["query"]),
        permissions=("browser:open", "network:egress"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="browser_sandbox",
        tags=("ecommerce", "browser"),
    ),
    SkillSpec(
        id="logistics.browser.tracking",
        name_zh="快递查询",
        name_en="Browser Logistics Tracking",
        domain="commerce_life",
        summary="Browser-assisted shipment tracking for user-provided tracking numbers.",
        entrypoint="panclaw.adapters.finance_life:browser_tracking",
        upstreams=(up("Selenium", "https://github.com/SeleniumHQ/selenium", "Apache-2.0", "optional_adapter"),),
        input_schema=schema({"tracking_number": {"type": "string"}, "carrier": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["tracking_number"]),
        permissions=("browser:open", "network:egress", "personal_data:process"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="browser_sandbox",
        tags=("logistics", "browser"),
    ),
    SkillSpec(
        id="food_delivery.browser.draft_order",
        name_zh="外卖草稿",
        name_en="Food Delivery Draft Order",
        domain="commerce_life",
        summary="Prepares a food delivery draft only; no payment or final order submission.",
        entrypoint="panclaw.adapters.finance_life:food_delivery_draft",
        upstreams=(up("Browser automation", "https://github.com/microsoft/playwright", "Apache-2.0", "optional_adapter"),),
        input_schema=schema({"restaurant": {"type": "string"}, "items": {"type": "array"}, "dry_run": {"type": "boolean"}}, ["restaurant", "items"]),
        permissions=("browser:open", "network:egress", "personal_data:process"),
        risk_level=RiskLevel.DESTRUCTIVE,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="browser_sandbox",
        tags=("food-delivery", "draft-only"),
    ),
    SkillSpec(
        id="health.biopython.process",
        name_zh="生物信息处理",
        name_en="BioPython Process",
        domain="health_medical",
        summary="Runs biological sequence processing through BioPython when installed.",
        entrypoint="panclaw.adapters.health_learning:biopython_process",
        upstreams=(up("BioPython", "https://github.com/biopython/biopython", "Biopython", "optional_adapter"),),
        input_schema=schema({"sequence": {"type": "string"}, "operation": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["sequence"]),
        permissions=("compute:local",),
        risk_level=RiskLevel.REGULATED,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        sandbox="local_process",
        tags=("health", "biology"),
        notes="Not medical diagnosis.",
    ),
    SkillSpec(
        id="medical.rag.search",
        name_zh="医学知识库检索",
        name_en="Medical RAG Search",
        domain="health_medical",
        summary="Searches a local medical knowledge base if configured.",
        entrypoint="panclaw.adapters.health_learning:medical_rag_search",
        upstreams=(up("Local medical datasets", "https://github.com/search?q=MedLLM+dataset&type=repositories", None, "local_dataset_review"),),
        input_schema=schema({"query": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["query"]),
        permissions=("filesystem:read", "vector_store:read"),
        risk_level=RiskLevel.REGULATED,
        status=SkillStatus.OFFICIAL_API_REQUIRED,
        sandbox="local_readonly",
        tags=("medical", "rag"),
        notes="Returns references and draft summaries only.",
    ),
    SkillSpec(
        id="learning.sympy.solve",
        name_zh="符号数学",
        name_en="SymPy Solve",
        domain="learning",
        summary="Solves symbolic math expressions through SymPy when installed.",
        entrypoint="panclaw.adapters.health_learning:sympy_solve",
        upstreams=(up("SymPy", "https://github.com/sympy/sympy", "BSD-3-Clause", "optional_adapter"),),
        input_schema=schema({"expression": {"type": "string"}, "variable": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["expression"]),
        permissions=("compute:local",),
        risk_level=RiskLevel.LOW,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        sandbox="local_process",
        tags=("math", "education"),
    ),
    SkillSpec(
        id="learning.kiwix.search",
        name_zh="离线百科检索",
        name_en="Kiwix Search",
        domain="learning",
        summary="Searches a local Kiwix/ZIM archive through an external CLI or service.",
        entrypoint="panclaw.adapters.health_learning:kiwix_search",
        upstreams=(up("Kiwix", "https://github.com/kiwix", "GPL/various", "external_cli_or_service"),),
        input_schema=schema({"query": {"type": "string"}, "archive": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["query"]),
        permissions=("filesystem:read", "subprocess:execute"),
        risk_level=RiskLevel.LOW,
        status=SkillStatus.LICENSE_GATED,
        sandbox="external_cli",
        license_boundary="external_process_only",
        tags=("kiwix", "offline-wiki"),
    ),
    SkillSpec(
        id="sports.scrapy.collect",
        name_zh="体育数据采集",
        name_en="Sports Scrapy Collect",
        domain="sports_military",
        summary="Runs approved sports data crawlers through Scrapy when configured.",
        entrypoint="panclaw.adapters.news_culture_aec:sports_scrapy_collect",
        upstreams=(up("Scrapy", "https://github.com/scrapy/scrapy", "BSD-3-Clause", "optional_adapter"),),
        input_schema=schema({"source": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["source"]),
        permissions=("network:egress",),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        approval_required=True,
        sandbox="crawler_sandbox",
        tags=("sports", "crawler"),
    ),
    SkillSpec(
        id="military.rss.brief",
        name_zh="军事公开 RSS 摘要",
        name_en="Military Public RSS Brief",
        domain="sports_military",
        summary="Summarizes public RSS items; no targeting, surveillance or operational guidance.",
        entrypoint="panclaw.adapters.news_culture_aec:military_rss_brief",
        input_schema=schema({"feeds": {"type": "array"}, "dry_run": {"type": "boolean"}}, ["feeds"]),
        permissions=("network:egress",),
        risk_level=RiskLevel.REGULATED,
        status=SkillStatus.READY,
        sandbox="network_readonly",
        tags=("rss", "public-news"),
        notes="Public news only.",
    ),
    SkillSpec(
        id="aec.freecad.script",
        name_zh="FreeCAD 脚本",
        name_en="FreeCAD Script",
        domain="aec_gis",
        summary="Runs FreeCAD Python scripts through an external FreeCAD runtime.",
        entrypoint="panclaw.adapters.news_culture_aec:freecad_script",
        upstreams=(up("FreeCAD", "https://github.com/FreeCAD/FreeCAD", "LGPL-2.0+", "external_cli"),),
        input_schema=schema({"script_path": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["script_path"]),
        permissions=("filesystem:read", "filesystem:write", "subprocess:execute"),
        risk_level=RiskLevel.HIGH,
        status=SkillStatus.LICENSE_GATED,
        approval_required=True,
        sandbox="external_cli",
        license_boundary="external_process_only",
        tags=("aec", "cad"),
    ),
    SkillSpec(
        id="gis.gdal.inspect",
        name_zh="GIS 数据检查",
        name_en="GDAL Inspect",
        domain="aec_gis",
        summary="Inspects geospatial data through GDAL bindings or CLI when installed.",
        entrypoint="panclaw.adapters.news_culture_aec:gdal_inspect",
        upstreams=(up("GDAL", "https://github.com/OSGeo/gdal", "MIT/X", "optional_or_external_cli"),),
        input_schema=schema({"path": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["path"]),
        permissions=("filesystem:read", "subprocess:execute"),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        sandbox="local_file_adapter",
        tags=("gis", "gdal"),
    ),
    SkillSpec(
        id="culture.lunar.compute",
        name_zh="历法与传统文化计算",
        name_en="Lunar Culture Compute",
        domain="culture_fengshui",
        summary="Computes lunar calendar/traditional-culture data through a reviewed local library.",
        entrypoint="panclaw.adapters.news_culture_aec:lunar_compute",
        upstreams=(
            up("lunar-python", "https://github.com/6tail/lunar-python", "MIT", "optional_adapter"),
            up("Lunar-Link verification", "https://github.com/search?q=Lunar-Link+%E7%B4%AB%E5%BE%AE%E6%96%97%E6%95%B0&type=repositories", None, "source_verification_required"),
        ),
        input_schema=schema({"date": {"type": "string"}, "mode": {"type": "string"}, "dry_run": {"type": "boolean"}}, ["date"]),
        permissions=("compute:local",),
        risk_level=RiskLevel.MEDIUM,
        status=SkillStatus.OPTIONAL_DEPENDENCY,
        sandbox="local_process",
        tags=("lunar", "fengshui", "calendar"),
        notes="Traditional-culture output is informational only.",
    ),
)
